services:
  # Backend API
  - type: web
    name: eleicao-api
    env: node
    plan: free
    buildCommand: |
      cd apps/api
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install --no-package-lock --no-audit --no-fund --legacy-peer-deps --force
      npm run build
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: "SUA_URL_DO_SUPABASE_AQUI"
      - key: SUPABASE_ANON_KEY
        value: "SUA_CHAVE_ANONIMA_AQUI"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "SUA_CHAVE_SERVICE_ROLE_AQUI"

  # Frontend Admin - Usando Yarn
  - type: web
    name: eleicao-admin
    env: static
    plan: free
    buildCommand: |
      cd apps/admin
      npm install -g yarn
      # Remover package.json raiz que causa conflito
      rm -f ../../package.json
      # Usar package-yarn.json
      cp package-yarn.json package.json
      # Criar arquivo .env.production com as URLs corretas
      echo "VITE_API_URL=https://preview-5pug.onrender.com/api" > .env.production
      echo "VITE_WEB_URL=https://surv-rkzx.onrender.com" >> .env.production
      rm -rf node_modules yarn.lock dist
      yarn install
      yarn build
    staticPublishPath: apps/admin/dist
    envVars:
      - key: VITE_API_URL
        value: https://preview-5pug.onrender.com/api
      - key: VITE_WEB_URL
        value: https://surv-rkzx.onrender.com
      - key: NODE_VERSION
        value: 18

  # Frontend Web - Usando Yarn
  - type: static
    name: eleicao-web
    env: static
    plan: free
    buildCommand: |
      cd apps/web
      npm install -g yarn
      # Remover package.json raiz que causa conflito
      rm -f ../../package.json
      # Usar package-yarn.json
      cp package-yarn.json package.json
      # Criar arquivo .env.production com a URL correta
      echo "VITE_API_URL=https://preview-5pug.onrender.com/api" > .env.production
      rm -rf node_modules yarn.lock dist
      yarn install
      yarn build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://preview-5pug.onrender.com/api
      - key: NODE_VERSION
        value: 18
